
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[258] =
    {   0,
        0,    0,    0,    0,   76,   74,    1,    2,   74,   74,
       61,   62,    7,   74,   63,   74,    6,    3,    5,   68,
       64,   70,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   74,   75,   67,   72,    0,
        0,    0,    0,   73,    0,   73,    3,    0,    0,    3,
       65,   66,   69,   60,   60,   60,   60,   60,   60,   46,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   56,   58,   60,   60,   60,   60,   60,   60,

       60,   16,   59,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,    0,   73,   73,   73,   73,    0,   73,
        4,   22,   48,   43,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   32,   60,   60,   60,   40,   41,   51,
       60,   60,   60,   60,   28,   60,   44,   60,   60,   60,
       60,   60,   60,    0,   73,   73,   73,   73,   73,   73,
        4,   60,   33,   60,   60,   60,   36,   49,   60,   10,
       12,   60,    8,   60,   20,   60,   60,    9,   60,   60,
       60,   60,   24,   39,   52,   35,   53,   60,   60,   60,

       17,   18,   60,   50,   60,   60,   60,    0,   29,   60,
       42,   60,   60,   60,   34,   45,   60,   15,   60,   38,
       60,   60,   47,   60,   60,   13,   60,   60,   21,    0,
       30,   11,   26,   57,   55,   37,   23,   60,   60,   19,
       14,   27,   25,    0,    0,    0,   60,   60,    0,   54,
       31,    0,    0,    0,    0,   71,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    1,    5,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   40,
        1,    1,    1,    1,   40,    1,   49,   25,   50,   27,

       28,   29,   51,   31,   52,   33,   34,   35,   53,   54,
       55,   39,   40,   41,   56,   57,   58,   59,   46,   60,
       48,   40,    1,   61,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[62] =
    {   0,
        1,    1,    1,    1,    2,    2,    3,    3,    4,    4,
        1,    5,    6,    5,    6,    6,    6,    6,    6,    1,
        1,    1,    1,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        7
    } ;

static const flex_int16_t yy_base[270] =
    {   0,
        0,    0,    0,    0,  152, 1159, 1159, 1159,   89,   57,
       54,   68,   74,   80, 1159,   88,  141,  147, 1159,   47,
     1159,   88,  160,  213,  152,  160,  164,  205,  158,  189,
      206,  143,   37,  217,  235,  230,  238,  242,  245,  253,
      208,  267,  187,   39,  272,  291,  216,  293,  310,  312,
      270,  317,  329,  315,  340,    0, 1159, 1159,  104,  103,
      364,  296,  383,  391,  446,    0,  424,  362,  431,    0,
     1159, 1159, 1159,  454,   43,  223,  368,  374,  429,   51,
      447,  458,  285,  357,  457,  470,  469,  472,  476,  481,
      487,  338,  520,  383,  502,  417,  516,  495,  524,  510,

      384,  511,  542,  538,  552,  543,  557,  560,  554,  556,
      579,  564,  573,  613,  626,    0,  634,  642,    0,  607,
      642,  589,  591,  617,  634,  635,  636,  640,  643,  650,
      625,  653,  657,  665,  676,  678,  684,  687,  681,  642,
      695,  647,  669,  702,  708,  690,  706,  713,  716,  718,
      720,  721,  723,  724,  725,  731,  732,  737,  746,  747,
      754,  748,  760,  794,  805,  813,  821,  827,  835,    0,
      835,  770,  798,  827,  820,  828,  810,  812,  838,  834,
      836,  844,  841,  845,  842,  852,  866,  850,  868,  869,
      871,  877,  878,  879,  881,  882,  907,  893,  911,  896,

      885,  895,  904,  909,  910,  912,  914,  177,  917,  920,
      921,  922,  923,  933,  926,  936,  948,  938,  944,  945,
      952,  954,  955,  963,  962,  966,  969,  973,  970, 1008,
      988,  992, 1000, 1002, 1003, 1004, 1005, 1006, 1009, 1010,
     1014, 1015, 1016, 1050, 1060,  182, 1032, 1045, 1066, 1042,
     1046, 1081, 1086,  180,   88,   76, 1159, 1105, 1111, 1115,
     1119, 1123, 1127, 1132, 1136, 1140, 1144, 1148, 1152
    } ;

static const flex_int16_t yy_def[270] =
    {   0,
      257,    1,  258,  258,  257,  257,  257,  257,  257,  259,
      260,  260,  260,  260,  257,  257,  260,  260,  257,  257,
      257,  257,  261,  261,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,  260,  257,  257,  259,  259,
      259,  260,  262,   16,  263,   64,   64,   64,   18,   18,
      257,  257,  257,  264,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,

       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,  259,  265,   64,  266,  266,  267,   64,
       18,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,  259,  268,  265,  265,  269,  266,  267,
       64,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,

       24,   24,   24,   24,   24,   24,   24,  259,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,  259,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,  259,  259,  259,   24,   24,  259,   24,
       24,  259,  259,  259,  259,  259,    0,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257
    } ;

static const flex_int16_t yy_nxt[1221] =
    {   0,
        6,    7,    8,    9,   10,    6,   11,   12,   13,   14,
       15,   16,   17,   14,   18,   18,   18,   18,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   33,   33,
       38,   39,   40,   41,   42,   43,   44,   33,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   33,
       56,   59,   63,   63,   75,   63,   75,   63,   71,   72,
       75,   61,   61,   61,   61,   61,   63,   63,   75,   63,
       59,   63,   63,   63,   75,   63,   75,   63,   63,   63,
       75,   63,  256,   63,   64,   64,   63,   63,   75,   65,

       66,   63,   67,   67,   67,   67,   67,   59,   59,   73,
       58,   64,   66,   64,   66,   66,   66,   64,   66,   64,
       66,   66,   66,   64,   64,   64,   66,   66,   66,   64,
       64,   64,   64,   66,   64,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   68,   63,
       63,  257,   63,  257,   63,   63,   63,  257,   63,   69,
       63,   70,   70,   70,   70,   70,   62,   62,   63,   63,
       75,   63,   62,   63,   74,   74,   74,   74,   74,   75,
       95,   59,   81,   84,  256,   75,   59,   85,  230,   82,
       75,   75,   83,  249,  255,  255,   76,   95,   90,   75,

       86,   77,  257,  257,   78,   75,   82,   75,   84,  257,
       87,   75,   91,   76,   75,   77,   92,  113,   78,   62,
       62,   63,   63,   87,   63,   62,   63,   74,   74,   74,
       74,   74,   75,   75,   75,   75,   75,   91,  257,   88,
       79,  257,   93,   75,   75,   89,  111,   94,   96,  122,
       75,  257,   75,   75,   97,   75,   90,   75,   98,   93,
       80,   94,   75,   75,   75,   75,   99,  100,   96,   75,
       75,   97,  105,  101,  102,  106,  109,   75,  103,  104,
      110,  257,   75,   98,  100,   75,   99,  101,  107,   75,
      112,  102,  108,  257,   75,  257,  104,   75,  257,   75,

       75,  109,  107,  257,   63,   63,  102,   63,   76,   63,
      103,  257,  129,   77,   75,  112,   78,   75,   75,   75,
       75,   81,  257,  102,  257,   76,  257,   77,   82,   93,
       78,   83,   75,   98,   94,  257,  257,   75,   75,   75,
       75,   99,   75,  257,  105,   82,   93,  106,   94,  100,
      257,  257,  109,  111,  257,  101,  110,   75,   98,   75,
      107,   99,   75,  112,  108,   75,  100,   75,   59,  101,
       62,   62,  139,   62,  107,   62,   75,  109,  114,  114,
      114,  114,  114,  257,   75,   75,  257,   75,  112,   62,
       62,   63,   63,  123,   63,   75,   63,   66,   66,  130,

      257,   75,   63,  124,   75,   66,   66,   66,   66,   66,
       75,   75,  257,  130,   66,   75,   66,  123,  151,  257,
       66,   75,   66,  257,  124,  257,   66,   66,   66,  257,
       75,   75,   66,   66,   66,   66,  120,   66,   67,   67,
       67,   67,   67,   62,   75,  121,  121,  121,  121,  121,
      146,  257,  116,  116,   63,   63,   75,   65,  125,   63,
       62,   62,   63,   63,   75,   63,   62,   63,  257,  118,
      126,  118,  257,  257,   75,  118,   75,  118,  257,  125,
      257,  118,  118,  118,   75,   75,  257,  118,  118,  118,
      118,  131,  118,  127,   75,  126,   75,   75,  132,   75,

      134,  128,  257,   75,   75,   75,  119,  133,   75,  135,
      127,  257,  132,  136,   75,  128,   75,   75,  137,   75,
      134,  257,   75,   75,  133,  257,  135,  257,   75,   75,
      136,  138,  257,  145,   75,  137,  257,   75,   75,  147,
      257,  148,   75,   75,  257,  138,  140,   75,  141,   75,
      257,   75,  150,  145,  148,  257,  142,   75,   75,  257,
      149,  143,  144,   75,  147,   75,  150,   75,  152,   75,
       75,   75,  153,  142,  257,  143,  144,  149,  159,   75,
      156,   75,  257,   75,   75,   75,  154,   75,  257,   75,
       75,   75,  157,  257,  155,  257,  158,  156,  162,   75,

      163,   75,  160,   75,   75,  161,   75,   75,  155,  157,
      257,   75,  257,  158,  257,  160,   75,   59,   75,  257,
       75,  171,  171,  171,  171,  171,   75,  164,  164,  164,
      164,  164,  165,  165,  166,  166,   75,  166,   75,  166,
      168,  168,  166,  166,   75,  166,  257,  166,  168,  168,
      166,  166,  179,  166,   62,  166,  121,  121,  121,  121,
      121,   75,   75,   75,   75,  172,  176,   75,  257,  189,
       75,  174,   75,  177,  191,  173,  175,  178,  180,  257,
       75,   75,   75,   75,   75,  172,  257,   75,  174,   75,
       75,  176,   75,  175,   75,  181,  192,   75,  177,  184,

       75,  257,  180,   75,   75,   75,  182,  183,   75,  257,
      257,   75,   75,  185,   75,  257,   75,  195,  187,  188,
      182,  183,   75,   75,  184,   75,  190,  186,   75,   75,
      185,   75,  196,   75,   75,   75,  257,   75,  187,  193,
       75,  186,   75,   75,  194,   75,  190,   75,  198,   75,
       75,  200,   75,   75,  197,   75,  193,  199,   75,   75,
       75,  194,  202,   75,   75,   75,  257,   75,   75,  257,
       75,   75,   75,   75,   75,   75,  201,  205,   75,   75,
      203,   75,  257,  257,   75,  257,  202,   75,  257,  204,
      257,  206,  257,   75,   75,   75,  257,   75,   59,  257,

      207,   75,  205,  204,  257,  206,  209,   75,  208,  208,
      208,  208,  208,  166,  166,  257,  166,   75,  166,  165,
      165,  166,  166,  209,  166,   75,  166,  165,  165,  166,
      166,  257,  166,  257,  166,  166,  166,   75,  166,   75,
      166,  168,  168,  166,  166,   75,  166,   75,  166,  171,
      171,  171,  171,  171,   75,   75,  257,   75,  210,   75,
      257,   75,  211,   75,  257,   75,  257,   75,   75,   75,
      212,   75,   75,  257,   75,   75,  211,   75,  210,   75,
      213,   75,  257,   75,  212,   75,  214,  215,   75,   75,
      216,   75,   75,   75,  213,   75,   75,   75,   75,   75,

      214,  215,  217,  219,   75,   75,   75,  257,   75,   75,
      257,  220,   75,   75,  218,   75,   75,  221,   75,  217,
       75,  225,   75,   75,   75,   75,   75,  218,   75,   75,
      222,  226,   75,  223,   75,  224,   75,   75,   75,  228,
       75,  229,   75,   75,   75,  225,  257,   75,   75,  232,
      233,   75,  227,   75,   75,  222,   75,   75,   75,   75,
       75,   75,  231,   75,   75,   75,  227,   75,   75,   75,
       75,  236,   75,   75,  234,   75,  231,  235,  238,   75,
       75,   75,   75,   75,  257,   75,  239,  257,  234,   75,
       75,   75,   75,   75,  237,   75,  242,   75,  235,   75,

       75,   75,   75,  257,  240,  257,  257,  241,  237,   75,
       75,  239,   59,   75,  243,   75,   75,   75,  240,   75,
       75,  241,  244,  245,  246,  246,  246,   75,  243,   75,
       75,   75,   75,   75,  248,   75,   75,   75,  257,   75,
      247,   75,   75,   75,  257,  257,  257,   75,  257,   75,
       75,   75,   75,   75,   59,  257,   75,   75,  248,  250,
      257,   75,   75,   75,   59,  246,  246,  246,  246,   75,
       59,  249,   75,   75,  246,  246,  246,  257,  251,   75,
      252,  253,  253,  254,  255,   59,  257,  257,  257,   75,
      256,  257,   75,   75,  257,  257,  255,  255,  255,  255,

      255,  255,  255,  255,  255,   57,   57,   57,   57,   57,
       57,   57,   60,  257,  257,   60,   60,   62,   62,   62,
       62,   75,   75,   75,   75,  115,  115,  115,  115,  117,
      117,  117,  117,  117,   74,   74,   74,   74,  167,  167,
      167,  167,  169,  169,  169,  169,  170,  257,  257,  170,
      165,  165,  165,  165,  168,  168,  168,  168,    5,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,

      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257
    } ;

static const flex_int16_t yy_chk[1221] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   10,   11,   11,   33,   11,   44,   11,   20,   20,
       75,   10,   10,   10,   10,   10,   12,   12,   80,   12,
      256,   12,   13,   13,   33,   13,   44,   13,   14,   14,
       75,   14,  255,   14,   16,   16,   16,   16,   80,   16,

       16,   16,   16,   16,   16,   16,   16,   60,   59,   22,
        9,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   17,
       17,    5,   17,    0,   17,   18,   18,    0,   18,   18,
       18,   18,   18,   18,   18,   18,   23,   23,   23,   23,
       32,   23,   23,   23,   23,   23,   23,   23,   23,   25,
       32,  208,   25,   26,  254,   29,  246,   26,  208,   25,
       32,   27,   25,  246,  254,  254,   23,   32,   29,   25,

       26,   23,    0,    0,   23,   29,   25,   26,   26,    0,
       27,   27,   30,   23,   43,   23,   30,   43,   23,   24,
       24,   24,   24,   27,   24,   24,   24,   24,   24,   24,
       24,   24,   28,   31,   43,   41,   30,   30,    0,   28,
       24,    0,   31,   47,   34,   28,   41,   31,   34,   76,
       76,    0,   28,   31,   34,   41,   47,   36,   35,   31,
       24,   31,   35,   47,   34,   37,   35,   36,   34,   38,
       76,   34,   39,   36,   37,   39,   40,   36,   37,   38,
       40,    0,   35,   35,   36,   37,   35,   36,   39,   38,
       42,   37,   39,    0,   42,    0,   38,   51,    0,   45,

       40,   40,   39,    0,   62,   62,   51,   62,   45,   62,
       51,    0,   83,   45,   42,   42,   45,   51,   46,   45,
       48,   46,    0,   51,    0,   45,    0,   45,   46,   48,
       45,   46,   83,   49,   48,    0,    0,   49,   46,   50,
       48,   49,   54,    0,   52,   46,   48,   52,   48,   50,
        0,    0,   53,   54,    0,   50,   53,   49,   49,   50,
       52,   49,   54,   55,   52,   92,   50,   55,   61,   50,
       68,   68,   92,   68,   52,   68,   53,   53,   61,   61,
       61,   61,   61,    0,   84,   92,    0,   55,   55,   63,
       63,   63,   63,   77,   63,   77,   63,   64,   64,   84,

        0,   78,   64,   78,   84,   64,   64,   64,   64,   64,
       94,  101,    0,   84,   64,   77,   64,   77,  101,    0,
       64,   78,   64,    0,   78,    0,   64,   64,   64,    0,
       94,  101,   64,   64,   64,   64,   67,   64,   67,   67,
       67,   67,   67,   69,   96,   69,   69,   69,   69,   69,
       96,   64,   65,   65,   65,   65,   79,   65,   79,   65,
       74,   74,   74,   74,   96,   74,   74,   74,    0,   65,
       81,   65,    0,    0,   81,   65,   79,   65,    0,   79,
        0,   65,   65,   65,   85,   82,    0,   65,   65,   65,
       65,   85,   65,   82,   81,   81,   87,   86,   85,   88,

       87,   82,    0,   89,   85,   82,   65,   86,   90,   88,
       82,    0,   85,   89,   91,   82,   87,   86,   90,   88,
       87,    0,   98,   89,   86,    0,   88,    0,   90,   95,
       89,   91,    0,   95,   91,   90,    0,  100,  102,   97,
        0,   98,   98,   97,    0,   91,   93,   93,   93,   95,
        0,   99,  100,   95,   98,    0,   93,  100,  102,    0,
       99,   93,   93,   97,   97,  104,  100,   93,  103,  103,
      106,   99,  104,   93,    0,   93,   93,   99,  109,  105,
      106,  109,    0,  110,  107,  104,  105,  108,    0,  103,
      106,  112,  107,    0,  105,    0,  108,  106,  112,  105,

      113,  109,  110,  110,  107,  111,  111,  108,  105,  107,
        0,  112,    0,  108,    0,  110,  122,  114,  123,    0,
      113,  120,  120,  120,  120,  120,  111,  114,  114,  114,
      114,  114,  115,  115,  115,  115,  122,  115,  123,  115,
      117,  117,  117,  117,  124,  117,    0,  117,  118,  118,
      118,  118,  131,  118,  121,  118,  121,  121,  121,  121,
      121,  125,  126,  127,  124,  125,  129,  128,    0,  140,
      129,  127,  131,  130,  142,  126,  128,  130,  132,    0,
      132,  125,  126,  127,  133,  125,    0,  128,  127,  140,
      129,  129,  134,  128,  142,  133,  143,  130,  130,  135,

      132,    0,  132,  135,  133,  136,  134,  134,  139,    0,
        0,  137,  134,  136,  138,    0,  143,  146,  138,  139,
      134,  134,  141,  135,  135,  136,  141,  137,  139,  144,
      136,  137,  147,  147,  138,  145,    0,  146,  138,  144,
      148,  137,  141,  149,  145,  150,  141,  151,  152,  144,
      153,  154,  155,  147,  151,  145,  144,  153,  156,  157,
      148,  145,  158,  149,  158,  150,    0,  151,  152,    0,
      153,  154,  155,  159,  160,  162,  156,  161,  156,  157,
      159,  161,    0,    0,  158,    0,  158,  163,    0,  160,
        0,  162,    0,  159,  160,  162,    0,  172,  164,    0,

      163,  161,  161,  160,    0,  162,  172,  163,  164,  164,
      164,  164,  164,  165,  165,    0,  165,  172,  165,  166,
      166,  166,  166,  172,  166,  173,  166,  167,  167,  167,
      167,    0,  167,    0,  167,  168,  168,  177,  168,  178,
      168,  169,  169,  169,  169,  173,  169,  175,  169,  171,
      171,  171,  171,  171,  174,  176,    0,  177,  174,  178,
        0,  180,  175,  181,    0,  179,    0,  175,  183,  185,
      176,  182,  184,    0,  174,  176,  175,  188,  174,  186,
      179,  180,    0,  181,  176,  179,  182,  184,  183,  185,
      186,  182,  184,  187,  179,  189,  190,  188,  191,  186,

      182,  184,  187,  190,  192,  193,  194,    0,  195,  196,
        0,  191,  201,  187,  189,  189,  190,  192,  191,  187,
      198,  200,  202,  200,  192,  193,  194,  189,  195,  196,
      197,  203,  201,  198,  197,  199,  204,  205,  199,  206,
      198,  207,  202,  200,  209,  200,    0,  210,  211,  212,
      213,  203,  205,  215,  197,  197,  204,  205,  199,  206,
      214,  207,  210,  216,  209,  218,  205,  210,  211,  212,
      213,  219,  220,  215,  214,  217,  210,  217,  222,  221,
      214,  222,  223,  216,    0,  218,  224,    0,  214,  225,
      224,  219,  220,  226,  221,  217,  227,  229,  217,  221,

      228,  222,  223,    0,  225,    0,    0,  226,  221,  225,
      224,  224,  230,  226,  228,  231,  227,  229,  225,  232,
      228,  226,  230,  230,  230,  230,  230,  233,  228,  234,
      235,  236,  237,  238,  239,  231,  239,  240,    0,  232,
      238,  241,  242,  243,    0,    0,    0,  233,    0,  234,
      235,  236,  237,  238,  244,    0,  239,  240,  239,  247,
        0,  241,  242,  243,  245,  244,  244,  244,  244,  250,
      249,  245,  248,  251,  245,  245,  245,    0,  248,  247,
      249,  249,  249,  249,  249,  252,    0,    0,    0,  250,
      253,    0,  248,  251,    0,    0,  252,  252,  252,  252,

      253,  253,  253,  253,  253,  258,  258,  258,  258,  258,
      258,  258,  259,    0,    0,  259,  259,  260,  260,  260,
      260,  261,  261,  261,  261,  262,  262,  262,  262,  263,
      263,  263,  263,  263,  264,  264,  264,  264,  265,  265,
      265,  265,  266,  266,  266,  266,  267,    0,    0,  267,
      268,  268,  268,  268,  269,  269,  269,  269,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,

      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lex_sql.l"
#line 2 "lex_sql.l"
#include<string.h>
#include<stdio.h>

struct ParserContext;

#include "yacc_sql.tab.h"
extern int atoi();
extern double atof();
#define YYDEBUG 1
#if YYDEBUG > 0
#define debug_printf  printf
#else
#define debug_printf(...)
#endif // YYDEBUG

#define RETURN_TOKEN(token) debug_printf("%s\n",#token);return token
#line 805 "lex.yy.c"
/* Prevent the need for linking with -lfl */

#line 808 "lex.yy.c"

#define INITIAL 0
#define STR 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  , yyscan_t yyscanner);
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 33 "lex_sql.l"


#line 1086 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 258 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1159 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 35 "lex_sql.l"
// ignore whitespace
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 36 "lex_sql.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "lex_sql.l"
yylval->number=atoi(yytext); RETURN_TOKEN(NUMBER);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "lex_sql.l"
yylval->floats=(float)(atof(yytext)); RETURN_TOKEN(FLOAT);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "lex_sql.l"
RETURN_TOKEN(SEMICOLON);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "lex_sql.l"
RETURN_TOKEN(DOT);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 43 "lex_sql.l"
RETURN_TOKEN(STAR);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 44 "lex_sql.l"
RETURN_TOKEN(EXIT);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 45 "lex_sql.l"
RETURN_TOKEN(HELP);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 46 "lex_sql.l"
RETURN_TOKEN(DESC);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 47 "lex_sql.l"
RETURN_TOKEN(CREATE);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 48 "lex_sql.l"
RETURN_TOKEN(DROP);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 49 "lex_sql.l"
RETURN_TOKEN(TABLE);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 50 "lex_sql.l"
RETURN_TOKEN(TABLES);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 51 "lex_sql.l"
RETURN_TOKEN(INDEX);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 52 "lex_sql.l"
RETURN_TOKEN(ON);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 53 "lex_sql.l"
RETURN_TOKEN(SHOW);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 54 "lex_sql.l"
RETURN_TOKEN(SYNC);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 55 "lex_sql.l"
RETURN_TOKEN(SELECT);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 56 "lex_sql.l"
RETURN_TOKEN(FROM);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 57 "lex_sql.l"
RETURN_TOKEN(WHERE);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 58 "lex_sql.l"
RETURN_TOKEN(AND);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "lex_sql.l"
RETURN_TOKEN(INSERT);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "lex_sql.l"
RETURN_TOKEN(INTO);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 61 "lex_sql.l"
RETURN_TOKEN(VALUES);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 62 "lex_sql.l"
RETURN_TOKEN(DELETE);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 63 "lex_sql.l"
RETURN_TOKEN(UPDATE);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 64 "lex_sql.l"
RETURN_TOKEN(SET);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 65 "lex_sql.l"
RETURN_TOKEN(TRX_BEGIN);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 66 "lex_sql.l"
RETURN_TOKEN(TRX_COMMIT);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 67 "lex_sql.l"
RETURN_TOKEN(TRX_ROLLBACK);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 68 "lex_sql.l"
RETURN_TOKEN(INT_T);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 69 "lex_sql.l"
RETURN_TOKEN(STRING_T);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 70 "lex_sql.l"
RETURN_TOKEN(FLOAT_T);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 71 "lex_sql.l"
RETURN_TOKEN(LOAD);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 72 "lex_sql.l"
RETURN_TOKEN(DATA);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 73 "lex_sql.l"
RETURN_TOKEN(INFILE);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 74 "lex_sql.l"
RETURN_TOKEN(INNER);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 75 "lex_sql.l"
RETURN_TOKEN(JOIN);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 76 "lex_sql.l"
RETURN_TOKEN(MAX);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 77 "lex_sql.l"
RETURN_TOKEN(MIN);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 78 "lex_sql.l"
RETURN_TOKEN(COUNT);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 79 "lex_sql.l"
RETURN_TOKEN(AVG);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 80 "lex_sql.l"
RETURN_TOKEN(SUM);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 81 "lex_sql.l"
RETURN_TOKEN(GROUP);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 82 "lex_sql.l"
RETURN_TOKEN(BY);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 83 "lex_sql.l"
RETURN_TOKEN(ORDER);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 84 "lex_sql.l"
RETURN_TOKEN(ASC);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 85 "lex_sql.l"
RETURN_TOKEN(DATE_T);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 86 "lex_sql.l"
RETURN_TOKEN(TEXT_T);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 87 "lex_sql.l"
RETURN_TOKEN(NOT);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 88 "lex_sql.l"
RETURN_TOKEN(LIKE);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 89 "lex_sql.l"
RETURN_TOKEN(NULL_TOKEN);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 90 "lex_sql.l"
RETURN_TOKEN(NULLABLE);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 91 "lex_sql.l"
RETURN_TOKEN(HAVING);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 92 "lex_sql.l"
RETURN_TOKEN(IN);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 93 "lex_sql.l"
RETURN_TOKEN(EXISTS);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 94 "lex_sql.l"
RETURN_TOKEN(IS);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 95 "lex_sql.l"
RETURN_TOKEN(OR);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 99 "lex_sql.l"
yylval->string=strdup(yytext); RETURN_TOKEN(ID);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 100 "lex_sql.l"
RETURN_TOKEN(LBRACE);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 101 "lex_sql.l"
RETURN_TOKEN(RBRACE);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 103 "lex_sql.l"
RETURN_TOKEN(COMMA);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 104 "lex_sql.l"
RETURN_TOKEN(EQ);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 105 "lex_sql.l"
RETURN_TOKEN(LE);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 106 "lex_sql.l"
RETURN_TOKEN(NE);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 107 "lex_sql.l"
RETURN_TOKEN(NE);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 108 "lex_sql.l"
RETURN_TOKEN(LT);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 109 "lex_sql.l"
RETURN_TOKEN(GE);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 110 "lex_sql.l"
RETURN_TOKEN(GT);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 113 "lex_sql.l"
yylval->string=strdup(yytext); RETURN_TOKEN(DATE_STR);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 114 "lex_sql.l"
yylval->string=strdup(yytext); RETURN_TOKEN(SSS);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 117 "lex_sql.l"
yylval->string=strdup(yytext);RETURN_TOKEN(EXPRESSION);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 119 "lex_sql.l"
printf("Unknown character [%c]\n",yytext[0]); return yytext[0];
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 120 "lex_sql.l"
ECHO;
	YY_BREAK
#line 1519 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 258 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 258 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 257);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 120 "lex_sql.l"


void scan_string(const char *str, yyscan_t scanner) {
  yy_switch_to_buffer(yy_scan_string(str, scanner), scanner);
}

